name: 機能要望
description: 新機能の提案
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## 重要: Issue作成前の確認事項
        Issue作成の前に、以下の手順で同様の提案がされていないか確認してください：
        1. [既存のIssue](https://github.com/tsuyoshi-otake-system-exe-jp/otak-monitor/issues)を検索
        2. 「Open」と「Closed」の両方のIssueを確認
        3. 類似のキーワードで検索

  - type: checkboxes
    id: prerequisites
    attributes:
      label: 事前確認
      options:
        - label: 既存のIssueを確認し、同様の提案がないことを確認しました
          required: true
        - label: 最新版の拡張機能の機能を確認しました
          required: true

  - type: input
    id: vscode-version
    attributes:
      label: Visual Studio Codeのバージョン
      description: VSCodeのバージョンを記入してください
      placeholder: "例：1.85.1"
    validations:
      required: true

  - type: input
    id: extension-version
    attributes:
      label: Otak Monitor拡張機能のバージョン
      description: 拡張機能のバージョンを記入してください
      placeholder: "例：1.1.1"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 関連する問題
      description: この機能要望に関連する問題や不便な点について説明してください
      placeholder: "例：現在のリソースモニタリングでは、特定のプロセスのみを監視することができない"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 提案する解決策
      description: どのような機能があれば良いか、具体的に説明してください
      placeholder: "例：監視対象のプロセスを選択できる機能を追加する"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案
      description: 検討した他の解決策があれば記入してください
      placeholder: "例：設定ファイルでプロセス名を指定する方法も検討したが..."
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: 追加情報
      description: 提案に関連する追加情報や参考資料があれば記入してください
    validations:
      required: false